/**
 * @file
 * VuoModuleCompilerResults interface.
 *
 * @copyright Copyright © 2012–2023 Kosada Incorporated.
 * This interface description may be modified and distributed under the terms of the GNU Lesser General Public License (LGPL) version 2 or later.
 * For more information, see https://vuo.org/license.
 */

#pragma once

class VuoMakeDependencies;

/**
 * The LLVM module and other artifacts produced by a VuoModuleCompiler.
 */
class VuoModuleCompilerResults
{
public:
	VuoModuleCompilerResults(void);

	Module *module;  ///< The compiled module.
	shared_ptr<VuoMakeDependencies> makeDependencies;  ///< The dependency file for the module, generated by the VuoModuleCompiler.
};
