/**
 * @file
 * VuoList_ExampleLanguage implementation.
 *
 * @copyright Copyright © 2012–2022 Kosada Incorporated.
 * This code may be modified and distributed under the terms of the MIT License.
 * For more information, see https://vuo.org/license.
 */

// This module is generated by vuo/type/list/generateVariants.sh.

extern "C" {
#include "VuoHeap.h"
#include "VuoInteger.h"
#include "VuoText.h"
#include "ExampleLanguage.h"
#include "VuoList_ExampleLanguage.h"
}
#include "type.h"
#include <string>
#include <sstream>
#include <vector>
#include <algorithm>

/// @{
/**
 * Ignore calls to VuoRetain and VuoRelease if the element type is not reference-counted.
 */
#if 0 == 0
#define RETAIN(element)
#define RELEASE(element)
#elif 0 == 1
#define RETAIN(element) VuoRetain((void *)element)
#define RELEASE(element) VuoRelease((void *)element)
#elif 0 == 2
#define RETAIN(element) ExampleLanguage_retain(element)
#define RELEASE(element) ExampleLanguage_release(element)
#endif
/// @}

extern "C" {
/// @{
#ifdef VUO_COMPILER
VuoModuleMetadata({
					 "title" : "List of ExampleLanguage elements",
					 "keywords" : [ ],
					 "version" : "1.0.0",
					 "dependencies" : [
						"VuoInteger",
						"ExampleLanguage"
					 ]
				 });
#endif
/// @}
}

/**
 * Destroys the list (a VuoList_ExampleLanguage).
 */
void VuoListDestroy_ExampleLanguage(void *list);


VuoList_ExampleLanguage VuoList_ExampleLanguage_makeFromJson(json_object * js)
{
	if (!js)
		return nullptr;

	VuoList_ExampleLanguage list = VuoListCreate_ExampleLanguage();

	if (json_object_get_type(js) == json_type_array)
	{
		int itemCount = json_object_array_length(js);
		for (int i = 0; i < itemCount; ++i)
		{
			json_object *itemObject = json_object_array_get_idx(js, i);
			ExampleLanguage item = ExampleLanguage_makeFromJson(itemObject);
			VuoListAppendValue_ExampleLanguage(list, item);
		}
	}

	return list;
}

json_object * VuoList_ExampleLanguage_getJson(const VuoList_ExampleLanguage value)
{
	if (!value)
		return nullptr;

	json_object *listObject = json_object_new_array();

	unsigned long itemCount = VuoListGetCount_ExampleLanguage(value);
	for (unsigned long i = 1; i <= itemCount; ++i)
	{
		ExampleLanguage item = VuoListGetValue_ExampleLanguage(value, i);
		json_object *itemObject = ExampleLanguage_getJson(item);
		json_object_array_add(listObject, itemObject);
	}

	return listObject;
}

#ifdef ExampleLanguage_REQUIRES_INTERPROCESS_JSON
struct json_object * VuoList_ExampleLanguage_getInterprocessJson(const VuoList_ExampleLanguage value)
{
	json_object *listObject = json_object_new_array();

	unsigned long itemCount = VuoListGetCount_ExampleLanguage(value);
	for (unsigned long i = 1; i <= itemCount; ++i)
	{
		ExampleLanguage item = VuoListGetValue_ExampleLanguage(value, i);
		json_object *itemObject = ExampleLanguage_getInterprocessJson(item);
		json_object_array_add(listObject, itemObject);
	}

	return listObject;
}
#endif

char * VuoList_ExampleLanguage_getSummary(const VuoList_ExampleLanguage value)
{
	const int maxItems = 20;
	const int maxCharacters = 400;

	unsigned long itemCount = VuoListGetCount_ExampleLanguage(value);
	if (itemCount == 0)
		return strdup("Empty list");

	unsigned long characterCount = 0;

	std::ostringstream summary;
	summary << "List containing " << itemCount << " item" << (itemCount == 1 ? "" : "s") << ": <ul>";
	unsigned long i;
	for (i = 1; i <= itemCount && i <= maxItems && characterCount <= maxCharacters; ++i)
	{
		ExampleLanguage item = VuoListGetValue_ExampleLanguage(value, i);
		char *itemSummaryCstr = ExampleLanguage_getSummary(item);
		std::string itemSummary = itemSummaryCstr;
		free(itemSummaryCstr);
		if (itemSummary.length() && itemSummary.find_first_not_of(' ') != std::string::npos)
			summary << "\n<li>" << itemSummary << "</li>";
		else
			summary << "\n<li>&nbsp;</li>";
		characterCount += itemSummary.length();
	}

	if (i <= itemCount)
		summary << "\n<li>…</li>";

	summary << "</ul>";

	return strdup(summary.str().c_str());
}

VuoList_ExampleLanguage VuoListCreate_ExampleLanguage(void)
{
	std::vector<ExampleLanguage> * l = new std::vector<ExampleLanguage>;
	VuoRegister(l, VuoListDestroy_ExampleLanguage);
	return reinterpret_cast<VuoList_ExampleLanguage>(l);
}

VuoList_ExampleLanguage VuoListCreateWithCount_ExampleLanguage(const unsigned long count, const ExampleLanguage value)
{
	std::vector<ExampleLanguage> * l = new std::vector<ExampleLanguage>(count, value);
	VuoRegister(l, VuoListDestroy_ExampleLanguage);

#if 0 != 0
	for (unsigned long i = 0; i < count; ++i)
		RETAIN(value);
#endif

	return reinterpret_cast<VuoList_ExampleLanguage>(l);
}

VuoList_ExampleLanguage VuoListCopy_ExampleLanguage(const VuoList_ExampleLanguage list)
{
	if (!list)
		return NULL;

	std::vector<ExampleLanguage> *oldList = (std::vector<ExampleLanguage> *)list;

	std::vector<ExampleLanguage> *newList = new std::vector<ExampleLanguage>(*oldList);
	VuoRegister(newList, VuoListDestroy_ExampleLanguage);

	for (std::vector<ExampleLanguage>::iterator i = newList->begin(); i != newList->end(); ++i)
		RETAIN(*i);

	return reinterpret_cast<VuoList_ExampleLanguage>(newList);
}

void VuoListDestroy_ExampleLanguage(void *list)
{
	if (!list)
		return;

#if 0 != 0
	VuoListRemoveAll_ExampleLanguage(reinterpret_cast<VuoList_ExampleLanguage>(list));
#endif

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;
	delete l;
}

ExampleLanguage VuoListGetValue_ExampleLanguage(const VuoList_ExampleLanguage list, const unsigned long index)
{
	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	if (!l || l->size() == 0)
		return ExampleLanguage_makeFromJson(NULL);

	if (index == 0)
		return (*l)[0];

	if (index > l->size())
		return (*l)[l->size()-1];

	return (*l)[index-1];
}

ExampleLanguage *VuoListGetData_ExampleLanguage(const VuoList_ExampleLanguage list)
{
	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	if (!l || l->size() == 0)
		return NULL;

	return &((*l)[0]);
}

void VuoListForeach_ExampleLanguage(const VuoList_ExampleLanguage list, bool (^function)(const ExampleLanguage value))
{
	auto l = reinterpret_cast<const std::vector<ExampleLanguage> *>(list);

	if (!l || l->size() == 0)
		return;

	for (auto item : *l)
		if (!function(item))
			break;
}

void VuoListSetValue_ExampleLanguage(const VuoList_ExampleLanguage list, const ExampleLanguage value, const unsigned long index, bool expandListIfNeeded)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	if (!expandListIfNeeded && l->size() == 0)
		return;

	unsigned long clampedIndex = index - 1;

	if (index == 0)
		clampedIndex = 0;

	if (expandListIfNeeded && clampedIndex >= l->size())
	{
		l->resize(clampedIndex + 1);
		(*l)[clampedIndex] = value;
		RETAIN(value);
	}
	else
	{
		if (index > l->size())
			clampedIndex = l->size() - 1;

#if 0 != 0
		ExampleLanguage oldValue = (*l)[clampedIndex];
#endif
		(*l)[clampedIndex] = value;
		RETAIN(value);
		RELEASE(oldValue);
	}
}

void VuoListInsertValue_ExampleLanguage(const VuoList_ExampleLanguage list, const ExampleLanguage value, const unsigned long index)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	unsigned long clampedIndex = index - 1;

	if (index == 0)
		clampedIndex = 0;

	if (index > l->size())
		clampedIndex = l->size() - 1;

	RETAIN(value);
	if (index <= l->size())
		l->insert(l->begin() + clampedIndex, value);
	else
		l->push_back(value);
}

void VuoListPrependValue_ExampleLanguage(VuoList_ExampleLanguage list, const ExampleLanguage value)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;
	RETAIN(value);
	l->insert(l->begin(), value);
}

void VuoListAppendValue_ExampleLanguage(VuoList_ExampleLanguage list, const ExampleLanguage value)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;
	RETAIN(value);
	l->push_back(value);
}

void VuoListExchangeValues_ExampleLanguage(VuoList_ExampleLanguage list, const unsigned long indexA, const unsigned long indexB)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	size_t size = l->size();
	if (size == 0)
		return;

	unsigned long clampedIndexA = indexA - 1;
	if (indexA == 0)
		clampedIndexA = 0;
	if (indexA > size)
		clampedIndexA = size - 1;

	unsigned long clampedIndexB = indexB - 1;
	if (indexB == 0)
		clampedIndexB = 0;
	if (indexB > size)
		clampedIndexB = size - 1;

	ExampleLanguage value = (*l)[clampedIndexA];
	(*l)[clampedIndexA] = (*l)[clampedIndexB];
	(*l)[clampedIndexB] = value;
}

#ifdef ExampleLanguage_SUPPORTS_COMPARISON
void VuoListSort_ExampleLanguage(VuoList_ExampleLanguage list)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	size_t size = l->size();
	if (size < 2)
		return;

	std::sort(l->begin(), l->end(), ExampleLanguage_isLessThan);
}

bool VuoList_ExampleLanguage_areEqual(const VuoList_ExampleLanguage _a, const VuoList_ExampleLanguage _b)
{
	if (_a == _b)
		return true;

	if (!_a || !_b)
		return _a == _b;

	std::vector<ExampleLanguage> *a = (std::vector<ExampleLanguage> *)_a;
	std::vector<ExampleLanguage> *b = (std::vector<ExampleLanguage> *)_b;
	if (a->size() != b->size())
		return false;

	for (std::vector<ExampleLanguage>::iterator ia = a->begin(), ib = b->begin(); ia != a->end(); ++ia, ++ib)
		if (!ExampleLanguage_areEqual(*ia, *ib))
			return false;

	return true;
}

bool VuoList_ExampleLanguage_isLessThan(const VuoList_ExampleLanguage _a, const VuoList_ExampleLanguage _b)
{
	if (!_a || !_b)
		return _a < _b;

	std::vector<ExampleLanguage> *a = (std::vector<ExampleLanguage> *)_a;
	std::vector<ExampleLanguage> *b = (std::vector<ExampleLanguage> *)_b;
	if (a->size() < b->size()) return true;
	if (a->size() > b->size()) return false;

	for (std::vector<ExampleLanguage>::iterator ia = a->begin(), ib = b->begin(); ia != a->end(); ++ia, ++ib)
	{
		if (ExampleLanguage_isLessThan(*ia, *ib)) return true;
		if (ExampleLanguage_isLessThan(*ib, *ia)) return false;
	}

	return false;
}
#endif

void VuoListShuffle_ExampleLanguage(VuoList_ExampleLanguage list, const double chaos)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	size_t size = l->size();
	if (size == 0)
		return;

	double clampedChaos = MIN(MAX(chaos,0),1);
	for (unsigned long i = 0; i < size * clampedChaos; ++i)
	{
		unsigned long j = VuoInteger_random(i, size-1);
		ExampleLanguage value = (*l)[i];
		(*l)[i] = (*l)[j];
		(*l)[j] = value;
	}
}

void VuoListReverse_ExampleLanguage(VuoList_ExampleLanguage list)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;
	std::reverse(l->begin(), l->end());
}

VuoList_ExampleLanguage VuoListSubset_ExampleLanguage(VuoList_ExampleLanguage list, const signed long startIndex, const unsigned long itemCount)
{
	if (!list)
		return NULL;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	size_t size = l->size();
	if (size == 0)
		return NULL;

	signed long clampedStartIndex = startIndex - 1;
	signed long clampedEndIndex = clampedStartIndex + itemCount - 1;

	if (clampedStartIndex < 0)
		clampedStartIndex = 0;
	if (clampedEndIndex >= (signed long)size)
		clampedEndIndex = size - 1;

	if (clampedStartIndex > clampedEndIndex)
		return NULL;

	std::vector<ExampleLanguage> *newList = new std::vector<ExampleLanguage>(
				l->begin() + clampedStartIndex,
				l->begin() + clampedEndIndex + 1);
	VuoRegister(newList, VuoListDestroy_ExampleLanguage);

	for (std::vector<ExampleLanguage>::iterator i = newList->begin(); i != newList->end(); ++i)
		RETAIN(*i);

	return reinterpret_cast<VuoList_ExampleLanguage>(newList);
}

#ifdef ExampleLanguage_SUPPORTS_COMPARISON
VuoList_ExampleLanguage VuoListRemoveDuplicates_ExampleLanguage(VuoList_ExampleLanguage list)
{
	if (!list)
		return NULL;

	auto *l = (std::vector<ExampleLanguage> *)list;

	size_t size = l->size();
	if (size == 0)
		return NULL;

	auto *newList = new std::vector<ExampleLanguage>;
	VuoRegister(newList, VuoListDestroy_ExampleLanguage);

	for (auto i = l->begin(); i != l->end(); ++i)
	{
		bool found = false;
		for (auto j = newList->begin(); j != newList->end(); ++j)
			if (ExampleLanguage_areEqual(*i, *j))
			{
				found = true;
				break;
			}
		if (!found)
			newList->push_back(*i);
	}

	for (auto i = newList->begin(); i != newList->end(); ++i)
		RETAIN(*i);

	return reinterpret_cast<VuoList_ExampleLanguage>(newList);
}
#endif

void VuoListRemoveFirstValue_ExampleLanguage(VuoList_ExampleLanguage list)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	if (!l->size())
		return;

	RELEASE(l->front());
	l->erase(l->begin());
}

void VuoListRemoveLastValue_ExampleLanguage(VuoList_ExampleLanguage list)
{
	if (!list)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	if (!l->size())
		return;

	RELEASE(l->back());
	l->pop_back();
}

void VuoListRemoveAll_ExampleLanguage(VuoList_ExampleLanguage list)
{
	if (!list)
		return;

	while (VuoListGetCount_ExampleLanguage(list) > 0)
		VuoListRemoveLastValue_ExampleLanguage(list);
}

void VuoListRemoveValue_ExampleLanguage(VuoList_ExampleLanguage list, const unsigned long index)
{
	if (!list)
		return;

	if (index == 0)
		return;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;

	size_t size = l->size();
	if (size == 0 || index > size)
		return;

	l->erase(l->begin() + index - 1);
}

unsigned long VuoListGetCount_ExampleLanguage(const VuoList_ExampleLanguage list)
{
	if (!list)
		return 0;

	std::vector<ExampleLanguage> * l = (std::vector<ExampleLanguage> *)list;
	return l->size();
}
